[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  UMBLER_HOST = "smtp.umbler.com"
  UMBLER_PORT = "587"
  UMBLER_SECURE = "false"
  UMBLER_USER = "contato@thunderglobalcorp.com"

  ZOHO_HOST = "smtp.zoho.com"
  ZOHO_PORT = "587"
  ZOHO_SECURE = "false"
  ZOHO_USER = "rh@thunderbank.com.br"
  RH_EMAIL = "rh@thunderbank.com.br"

# Redirecionamento SPA padr√£o
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
